// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20260410084404_A")]
    partial class A
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaterialMaterialBeställning", b =>
                {
                    b.Property<int>("MaterialBeställningID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialListaMaterialID")
                        .HasColumnType("int");

                    b.HasKey("MaterialBeställningID", "MaterialListaMaterialID");

                    b.HasIndex("MaterialListaMaterialID");

                    b.ToTable("MaterialMaterialBeställning");
                });

            modelBuilder.Entity("MaterialProdukt", b =>
                {
                    b.Property<int>("MaterialListaMaterialID")
                        .HasColumnType("int");

                    b.Property<int>("ProduktID")
                        .HasColumnType("int");

                    b.HasKey("MaterialListaMaterialID", "ProduktID");

                    b.HasIndex("ProduktID");

                    b.ToTable("MaterialProdukt");
                });

            modelBuilder.Entity("Models.Användare", b =>
                {
                    b.Property<int>("AnvändarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnvändarID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lösenord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnvändarID");

                    b.ToTable("Användare");
                });

            modelBuilder.Entity("Models.Kund", b =>
                {
                    b.Property<int>("KundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KundID"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KundID");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("Models.Material", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lagerantal")
                        .HasColumnType("int");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialID");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("Models.MaterialBeställning", b =>
                {
                    b.Property<int>("MaterialBeställningID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialBeställningID"));

                    b.Property<int>("StartadAvID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPris")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaterialBeställningID");

                    b.HasIndex("StartadAvID");

                    b.ToTable("MaterialBeställningar");
                });

            modelBuilder.Entity("Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Färdig")
                        .HasColumnType("bit");

                    b.Property<int>("KundID")
                        .HasColumnType("int");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StartadAvID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("KundID");

                    b.HasIndex("StartadAvID");

                    b.ToTable("Ordrar");
                });

            modelBuilder.Entity("Models.Produkt", b =>
                {
                    b.Property<int>("ProduktID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduktID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("ProduktTyp")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Storlek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TillverkadAVID")
                        .HasColumnType("int");

                    b.Property<string>("namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("pris")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProduktID");

                    b.HasIndex("OrderID");

                    b.HasIndex("TillverkadAVID");

                    b.ToTable("Produkter");

                    b.HasDiscriminator<string>("ProduktTyp").HasValue("Produkt");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Models.LagerfördProdukt", b =>
                {
                    b.HasBaseType("Models.Produkt");

                    b.Property<string>("ArtikelID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lagerantal")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Lagerförd");
                });

            modelBuilder.Entity("Models.SpecialBeställning", b =>
                {
                    b.HasBaseType("Models.Produkt");

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BildURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Special");
                });

            modelBuilder.Entity("MaterialMaterialBeställning", b =>
                {
                    b.HasOne("Models.MaterialBeställning", null)
                        .WithMany()
                        .HasForeignKey("MaterialBeställningID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialListaMaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaterialProdukt", b =>
                {
                    b.HasOne("Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialListaMaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Produkt", null)
                        .WithMany()
                        .HasForeignKey("ProduktID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.MaterialBeställning", b =>
                {
                    b.HasOne("Models.Användare", "StartadAv")
                        .WithMany("materialBeställningsLista")
                        .HasForeignKey("StartadAvID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StartadAv");
                });

            modelBuilder.Entity("Models.Order", b =>
                {
                    b.HasOne("Models.Kund", "Kund")
                        .WithMany("Orders")
                        .HasForeignKey("KundID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Användare", "StartadAv")
                        .WithMany("orderLista")
                        .HasForeignKey("StartadAvID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kund");

                    b.Navigation("StartadAv");
                });

            modelBuilder.Entity("Models.Produkt", b =>
                {
                    b.HasOne("Models.Order", "Order")
                        .WithMany("Produkter")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Användare", "TillverkadAv")
                        .WithMany("produktLista")
                        .HasForeignKey("TillverkadAVID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("TillverkadAv");
                });

            modelBuilder.Entity("Models.Användare", b =>
                {
                    b.Navigation("materialBeställningsLista");

                    b.Navigation("orderLista");

                    b.Navigation("produktLista");
                });

            modelBuilder.Entity("Models.Kund", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Models.Order", b =>
                {
                    b.Navigation("Produkter");
                });
#pragma warning restore 612, 618
        }
    }
}
