// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DBcontext))]
    [Migration("20260429115116_3")]
    partial class _3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AktivitetAnvändare", b =>
                {
                    b.Property<int>("DeltagareAnvändarID")
                        .HasColumnType("int");

                    b.Property<int>("DeltarIAktiviteterAktivitetID")
                        .HasColumnType("int");

                    b.HasKey("DeltagareAnvändarID", "DeltarIAktiviteterAktivitetID");

                    b.HasIndex("DeltarIAktiviteterAktivitetID");

                    b.ToTable("AnvändarAktiviteter", (string)null);
                });

            modelBuilder.Entity("MaterialMaterialBeställning", b =>
                {
                    b.Property<int>("MaterialBeställningID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialListaMaterialID")
                        .HasColumnType("int");

                    b.HasKey("MaterialBeställningID", "MaterialListaMaterialID");

                    b.HasIndex("MaterialListaMaterialID");

                    b.ToTable("MaterialMaterialBeställning");

                    b.HasData(
                        new
                        {
                            MaterialBeställningID = 1000001,
                            MaterialListaMaterialID = 100001
                        },
                        new
                        {
                            MaterialBeställningID = 1000001,
                            MaterialListaMaterialID = 100003
                        },
                        new
                        {
                            MaterialBeställningID = 1000002,
                            MaterialListaMaterialID = 100002
                        },
                        new
                        {
                            MaterialBeställningID = 1000002,
                            MaterialListaMaterialID = 100004
                        },
                        new
                        {
                            MaterialBeställningID = 1000003,
                            MaterialListaMaterialID = 100001
                        },
                        new
                        {
                            MaterialBeställningID = 1000003,
                            MaterialListaMaterialID = 100005
                        });
                });

            modelBuilder.Entity("MaterialProdukt", b =>
                {
                    b.Property<int>("MaterialListaMaterialID")
                        .HasColumnType("int");

                    b.Property<int>("ProduktID")
                        .HasColumnType("int");

                    b.HasKey("MaterialListaMaterialID", "ProduktID");

                    b.HasIndex("ProduktID");

                    b.ToTable("MaterialProdukt");

                    b.HasData(
                        new
                        {
                            MaterialListaMaterialID = 100001,
                            ProduktID = 10000001
                        },
                        new
                        {
                            MaterialListaMaterialID = 100003,
                            ProduktID = 10000001
                        },
                        new
                        {
                            MaterialListaMaterialID = 100005,
                            ProduktID = 10000001
                        },
                        new
                        {
                            MaterialListaMaterialID = 100004,
                            ProduktID = 10000002
                        },
                        new
                        {
                            MaterialListaMaterialID = 100003,
                            ProduktID = 10000002
                        },
                        new
                        {
                            MaterialListaMaterialID = 100002,
                            ProduktID = 10000003
                        },
                        new
                        {
                            MaterialListaMaterialID = 100005,
                            ProduktID = 10000003
                        },
                        new
                        {
                            MaterialListaMaterialID = 100004,
                            ProduktID = 10000004
                        },
                        new
                        {
                            MaterialListaMaterialID = 100002,
                            ProduktID = 10000004
                        },
                        new
                        {
                            MaterialListaMaterialID = 100003,
                            ProduktID = 10000004
                        });
                });

            modelBuilder.Entity("Models.Aktivitet", b =>
                {
                    b.Property<int>("AktivitetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AktivitetID"));

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkapadAvID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SlutTid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTid")
                        .HasColumnType("datetime2");

                    b.HasKey("AktivitetID");

                    b.HasIndex("SkapadAvID");

                    b.ToTable("Aktiviteter");
                });

            modelBuilder.Entity("Models.Användare", b =>
                {
                    b.Property<int>("AnvändarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnvändarID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Lösenord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnvändarID");

                    b.ToTable("Användare");

                    b.HasData(
                        new
                        {
                            AnvändarID = 1,
                            Email = "ottoHattman@hotmail.com",
                            IsActive = true,
                            IsAdmin = true,
                            Lösenord = "$2a$11$Sm4gPznXLP7ATihoEf1ZF.GQpuCBikGa1bb1jhElNgKyeL7asIC5O",
                            Namn = "Otto",
                            Telefon = "07085652321"
                        },
                        new
                        {
                            AnvändarID = 2,
                            Email = "JudithHattman@hotmail.com",
                            IsActive = true,
                            IsAdmin = false,
                            Lösenord = "$2a$11$Sm4gPznXLP7ATihoEf1ZF.GQpuCBikGa1bb1jhElNgKyeL7asIC5O",
                            Namn = "Judith",
                            Telefon = "0727639856"
                        },
                        new
                        {
                            AnvändarID = 3,
                            Email = "MillieHattman@hotmail.com",
                            IsActive = true,
                            IsAdmin = false,
                            Lösenord = "$2a$11$Sm4gPznXLP7ATihoEf1ZF.GQpuCBikGa1bb1jhElNgKyeL7asIC5O",
                            Namn = "Millie",
                            Telefon = "0709825533"
                        },
                        new
                        {
                            AnvändarID = 4,
                            Email = "HerbertHattman@hotmail.com",
                            IsActive = true,
                            IsAdmin = false,
                            Lösenord = "$2a$11$Sm4gPznXLP7ATihoEf1ZF.GQpuCBikGa1bb1jhElNgKyeL7asIC5O",
                            Namn = "Herbert",
                            Telefon = "0705512322"
                        });
                });

            modelBuilder.Entity("Models.BestallningsRad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<int>("MaterialBeställningID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialBeställningID");

                    b.HasIndex("MaterialId");

                    b.ToTable("BestallningsRader");

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            Antal = 20,
                            MaterialBeställningID = 1000001,
                            MaterialId = 100001
                        },
                        new
                        {
                            Id = 10002,
                            Antal = 10,
                            MaterialBeställningID = 1000001,
                            MaterialId = 100003
                        },
                        new
                        {
                            Id = 10003,
                            Antal = 30,
                            MaterialBeställningID = 1000002,
                            MaterialId = 100002
                        },
                        new
                        {
                            Id = 10004,
                            Antal = 12,
                            MaterialBeställningID = 1000002,
                            MaterialId = 100004
                        },
                        new
                        {
                            Id = 10005,
                            Antal = 35,
                            MaterialBeställningID = 1000003,
                            MaterialId = 100001
                        },
                        new
                        {
                            Id = 10006,
                            Antal = 15,
                            MaterialBeställningID = 1000003,
                            MaterialId = 100005
                        });
                });

            modelBuilder.Entity("Models.Kund", b =>
                {
                    b.Property<int>("KundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KundID"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FöretagsKund")
                        .HasColumnType("bit");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KundID");

                    b.ToTable("Kunder");

                    b.HasData(
                        new
                        {
                            KundID = 1001,
                            Adress = "Kullstigen 78",
                            Email = "Per.Larsson@hotmail.com",
                            FöretagsKund = true,
                            Land = "Sverige",
                            Namn = "Per Larsson",
                            Stad = "Stockholm",
                            Telefon = "076312129"
                        },
                        new
                        {
                            KundID = 1002,
                            Adress = "Milvägen 1",
                            Email = "Eva.Milen@hotmail.com",
                            FöretagsKund = true,
                            Land = "Sverige",
                            Namn = "Eva Von Milen",
                            Stad = "Stockholm",
                            Telefon = "0727728432"
                        },
                        new
                        {
                            KundID = 1003,
                            Adress = "Fjordaberg 51",
                            Email = "yvonne.fjord@hotmail.com",
                            FöretagsKund = false,
                            Land = "Finland",
                            Namn = "Yvonne Fjord",
                            Stad = "Helsingfors",
                            Telefon = "0702127345"
                        },
                        new
                        {
                            KundID = 1004,
                            Adress = "Javatorget 23",
                            Email = "ahmed.khan@hotmail.com",
                            FöretagsKund = false,
                            Land = "Sverige",
                            Namn = "Ahmed Khan",
                            Stad = "Örebro",
                            Telefon = "070123382"
                        },
                        new
                        {
                            KundID = 1005,
                            Adress = "Tetornet 3",
                            Email = "jasmin.barsk@hotmail.com",
                            FöretagsKund = false,
                            Land = "Sverige",
                            Namn = "Jasmin Barsk",
                            Stad = "Stockholm",
                            Telefon = "0702427373"
                        });
                });

            modelBuilder.Entity("Models.Material", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lagerantal")
                        .HasColumnType("int");

                    b.Property<int>("MåttTyp")
                        .HasColumnType("int");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaterialID");

                    b.ToTable("Material");

                    b.HasData(
                        new
                        {
                            MaterialID = 100001,
                            Beskrivning = "Inte filt man sover med",
                            Lagerantal = 23,
                            MåttTyp = 0,
                            Namn = "Filt",
                            Pris = 54m
                        },
                        new
                        {
                            MaterialID = 100002,
                            Beskrivning = "100% obesprutat bomull",
                            Lagerantal = 52,
                            MåttTyp = 0,
                            Namn = "Bomull",
                            Pris = 34m
                        },
                        new
                        {
                            MaterialID = 100003,
                            Beskrivning = "1.2 mm svar syträd av silikon och polyester",
                            Lagerantal = 2,
                            MåttTyp = 0,
                            Namn = "Svart tråd",
                            Pris = 28m
                        },
                        new
                        {
                            MaterialID = 100004,
                            Beskrivning = "Tunt siden till foder och detaljer",
                            Lagerantal = 18,
                            MåttTyp = 0,
                            Namn = "Siden",
                            Pris = 89m
                        },
                        new
                        {
                            MaterialID = 100005,
                            Beskrivning = "Brunt läderband till hattdekoration",
                            Lagerantal = 11,
                            MåttTyp = 0,
                            Namn = "Läderband",
                            Pris = 45m
                        });
                });

            modelBuilder.Entity("Models.MaterialBeställning", b =>
                {
                    b.Property<int>("MaterialBeställningID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialBeställningID"));

                    b.Property<DateTime?>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Leverantör")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartadAvID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPris")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaterialBeställningID");

                    b.HasIndex("StartadAvID");

                    b.ToTable("MaterialBeställningar");

                    b.HasData(
                        new
                        {
                            MaterialBeställningID = 1000001,
                            Datum = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Leverantör = "Kung AB",
                            StartadAvID = 1,
                            TotalPris = 1890m
                        },
                        new
                        {
                            MaterialBeställningID = 1000002,
                            Datum = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Leverantör = "Nordic Textile",
                            StartadAvID = 2,
                            TotalPris = 769m
                        },
                        new
                        {
                            MaterialBeställningID = 1000003,
                            Datum = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Leverantör = "Skrädderi Grossisten",
                            StartadAvID = 1,
                            TotalPris = 3419m
                        });
                });

            modelBuilder.Entity("Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Färdig")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FörväntadTillverkningsTid")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrio")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpecialbeställning")
                        .HasColumnType("bit");

                    b.Property<int>("KundID")
                        .HasColumnType("int");

                    b.Property<double?>("Moms")
                        .HasColumnType("float");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rabatt")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StartadAvID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Varukod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.HasIndex("KundID");

                    b.HasIndex("StartadAvID");

                    b.ToTable("Ordrar");

                    b.HasData(
                        new
                        {
                            OrderID = 100000001,
                            Datum = new DateTime(2024, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1001,
                            Pris = 1299m,
                            Rabatt = 0m,
                            StartadAvID = 1,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000002,
                            Datum = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1002,
                            Pris = 1099m,
                            Rabatt = 0m,
                            StartadAvID = 1,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000003,
                            Datum = new DateTime(2024, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1003,
                            Pris = 299m,
                            Rabatt = 0m,
                            StartadAvID = 1,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000004,
                            Datum = new DateTime(2024, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1004,
                            Pris = 2399m,
                            Rabatt = 0m,
                            StartadAvID = 1,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000005,
                            Datum = new DateTime(2024, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1005,
                            Pris = 779m,
                            Rabatt = 0m,
                            StartadAvID = 1,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000006,
                            Datum = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1001,
                            Pris = 949m,
                            Rabatt = 0m,
                            StartadAvID = 2,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000007,
                            Datum = new DateTime(2025, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1002,
                            Pris = 1049m,
                            Rabatt = 0m,
                            StartadAvID = 2,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000008,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1003,
                            Pris = 749m,
                            Rabatt = 0m,
                            StartadAvID = 2,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000009,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1004,
                            Pris = 999m,
                            Rabatt = 0m,
                            StartadAvID = 2,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000010,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1004,
                            Pris = 899m,
                            Rabatt = 0m,
                            StartadAvID = 2,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000011,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1005,
                            Pris = 1099m,
                            Rabatt = 0m,
                            StartadAvID = 2,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000012,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1001,
                            Pris = 2019m,
                            Rabatt = 0m,
                            StartadAvID = 3,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000013,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1002,
                            Pris = 1829m,
                            Rabatt = 0m,
                            StartadAvID = 3,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000014,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1003,
                            Pris = 599m,
                            Rabatt = 0m,
                            StartadAvID = 3,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000015,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1004,
                            Pris = 899m,
                            Rabatt = 0m,
                            StartadAvID = 3,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000016,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1005,
                            Pris = 1299m,
                            Rabatt = 0m,
                            StartadAvID = 3,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000017,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1001,
                            Pris = 499m,
                            Rabatt = 0m,
                            StartadAvID = 4,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000018,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1002,
                            Pris = 499m,
                            Rabatt = 0m,
                            StartadAvID = 4,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000019,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1003,
                            Pris = 499m,
                            Rabatt = 0m,
                            StartadAvID = 4,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000020,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1004,
                            Pris = 499m,
                            Rabatt = 0m,
                            StartadAvID = 4,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        },
                        new
                        {
                            OrderID = 100000021,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1005,
                            Pris = 499m,
                            Rabatt = 0m,
                            StartadAvID = 4,
                            Status = "Ej påbörjat",
                            Varukod = ""
                        });
                });

            modelBuilder.Entity("Models.OrderRad", b =>
                {
                    b.Property<int>("OrderRadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderRadID"));

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProduktID")
                        .HasColumnType("int");

                    b.HasKey("OrderRadID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProduktID");

                    b.ToTable("OrderRader");

                    b.HasData(
                        new
                        {
                            OrderRadID = 20001,
                            Antal = 1,
                            OrderID = 100000001,
                            ProduktID = 10000004
                        },
                        new
                        {
                            OrderRadID = 20002,
                            Antal = 1,
                            OrderID = 100000002,
                            ProduktID = 10000001
                        },
                        new
                        {
                            OrderRadID = 20003,
                            Antal = 1,
                            OrderID = 100000003,
                            ProduktID = 10000003
                        },
                        new
                        {
                            OrderRadID = 20004,
                            Antal = 1,
                            OrderID = 100000004,
                            ProduktID = 10000004
                        },
                        new
                        {
                            OrderRadID = 20005,
                            Antal = 1,
                            OrderID = 100000005,
                            ProduktID = 10000002
                        },
                        new
                        {
                            OrderRadID = 20006,
                            Antal = 1,
                            OrderID = 100000006,
                            ProduktID = 10000002
                        },
                        new
                        {
                            OrderRadID = 20007,
                            Antal = 1,
                            OrderID = 100000007,
                            ProduktID = 10000001
                        },
                        new
                        {
                            OrderRadID = 20008,
                            Antal = 2,
                            OrderID = 100000008,
                            ProduktID = 10000003
                        },
                        new
                        {
                            OrderRadID = 20009,
                            Antal = 1,
                            OrderID = 100000009,
                            ProduktID = 10000001
                        },
                        new
                        {
                            OrderRadID = 20010,
                            Antal = 1,
                            OrderID = 100000010,
                            ProduktID = 10000002
                        },
                        new
                        {
                            OrderRadID = 20011,
                            Antal = 1,
                            OrderID = 100000011,
                            ProduktID = 10000001
                        },
                        new
                        {
                            OrderRadID = 20012,
                            Antal = 1,
                            OrderID = 100000012,
                            ProduktID = 10000004
                        },
                        new
                        {
                            OrderRadID = 20013,
                            Antal = 1,
                            OrderID = 100000013,
                            ProduktID = 10000004
                        },
                        new
                        {
                            OrderRadID = 20014,
                            Antal = 1,
                            OrderID = 100000014,
                            ProduktID = 10000003
                        },
                        new
                        {
                            OrderRadID = 20015,
                            Antal = 1,
                            OrderID = 100000015,
                            ProduktID = 10000002
                        },
                        new
                        {
                            OrderRadID = 20016,
                            Antal = 1,
                            OrderID = 100000016,
                            ProduktID = 10000004
                        },
                        new
                        {
                            OrderRadID = 20017,
                            Antal = 1,
                            OrderID = 100000017,
                            ProduktID = 10000003
                        },
                        new
                        {
                            OrderRadID = 20018,
                            Antal = 1,
                            OrderID = 100000018,
                            ProduktID = 10000001
                        },
                        new
                        {
                            OrderRadID = 20019,
                            Antal = 1,
                            OrderID = 100000019,
                            ProduktID = 10000002
                        },
                        new
                        {
                            OrderRadID = 20020,
                            Antal = 1,
                            OrderID = 100000020,
                            ProduktID = 10000003
                        },
                        new
                        {
                            OrderRadID = 20021,
                            Antal = 1,
                            OrderID = 100000021,
                            ProduktID = 10000001
                        });
                });

            modelBuilder.Entity("Models.Planering", b =>
                {
                    b.Property<int>("PlaneringsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaneringsID"));

                    b.Property<int>("AnvändarID")
                        .HasColumnType("int");

                    b.Property<int>("OrderRadID")
                        .HasColumnType("int");

                    b.Property<string>("PlaneringsNamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SlutTid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTid")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlaneringsID");

                    b.HasIndex("AnvändarID");

                    b.HasIndex("OrderRadID");

                    b.ToTable("Planeringar");
                });

            modelBuilder.Entity("Models.Produkt", b =>
                {
                    b.Property<int>("ProduktID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduktID"));

                    b.Property<string>("Decoration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Färdig")
                        .HasColumnType("bit");

                    b.Property<string>("Färg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HattTyp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lagerantal")
                        .HasColumnType("int");

                    b.Property<string>("Modell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProduktTyp")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Storlek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TillverkadAVID")
                        .HasColumnType("int");

                    b.HasKey("ProduktID");

                    b.HasIndex("TillverkadAVID");

                    b.ToTable("Produkter");

                    b.HasDiscriminator<string>("ProduktTyp").HasValue("Produkt");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Models.Reklamation", b =>
                {
                    b.Property<int>("ReklamationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReklamationID"));

                    b.Property<string>("Atgard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AvslutadDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KundID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("Orsak")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProduktID")
                        .HasColumnType("int");

                    b.Property<int>("SkapadAvID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SkapadDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReklamationID");

                    b.HasIndex("KundID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProduktID");

                    b.HasIndex("SkapadAvID");

                    b.ToTable("Reklamationer");

                    b.HasData(
                        new
                        {
                            ReklamationID = 30001,
                            Atgard = "Justering",
                            Beskrivning = "Kunden önskar justering av passform.",
                            KundID = 1003,
                            OrderID = 100000008,
                            Orsak = "Fel storlek",
                            ProduktID = 10000003,
                            SkapadAvID = 1,
                            SkapadDatum = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Ny"
                        },
                        new
                        {
                            ReklamationID = 30002,
                            Atgard = "Reparation",
                            Beskrivning = "Sidenrosetten behöver bytas till ljusare nyans.",
                            KundID = 1002,
                            OrderID = 100000013,
                            Orsak = "Fel färg",
                            ProduktID = 10000004,
                            SkapadAvID = 2,
                            SkapadDatum = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Under behandling"
                        });
                });

            modelBuilder.Entity("Models.LagerfördProdukt", b =>
                {
                    b.HasBaseType("Models.Produkt");

                    b.Property<string>("ArtikelID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Lagerförd");

                    b.HasData(
                        new
                        {
                            ProduktID = 10000001,
                            Decoration = "Läderband",
                            Färdig = true,
                            Färg = "Svart",
                            HattTyp = "Fedora",
                            Lagerantal = 7,
                            Modell = "Klassisk",
                            Namn = "Filt hatt",
                            Pris = 1099m,
                            Storlek = "M",
                            TillverkadAVID = 1,
                            ArtikelID = "LP0001",
                            Kategori = "Hatt"
                        },
                        new
                        {
                            ProduktID = 10000002,
                            Decoration = "Svart tråd",
                            Färdig = true,
                            Färg = "Blå",
                            HattTyp = "Keps",
                            Lagerantal = 5,
                            Modell = "Siden",
                            Namn = "Siden keps",
                            Pris = 949m,
                            Storlek = "M",
                            TillverkadAVID = 2,
                            ArtikelID = "LP0002",
                            Kategori = "Keps"
                        },
                        new
                        {
                            ProduktID = 10000003,
                            Decoration = "Bomullsband",
                            Färdig = true,
                            Färg = "Naturvit",
                            HattTyp = "Panama",
                            Lagerantal = 4,
                            Modell = "Sommar",
                            Namn = "Sommarhatt",
                            Pris = 799m,
                            Storlek = "L",
                            TillverkadAVID = 3,
                            ArtikelID = "LP0003",
                            Kategori = "Hatt"
                        });
                });

            modelBuilder.Entity("Models.SpecialBeställning", b =>
                {
                    b.HasBaseType("Models.Produkt");

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BildURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Special");

                    b.HasData(
                        new
                        {
                            ProduktID = 10000004,
                            Decoration = "Sidenrosett",
                            Färdig = false,
                            Färg = "Creme",
                            HattTyp = "Fascinator",
                            Lagerantal = 0,
                            Modell = "Bröllop",
                            Namn = "Bröllopshatt",
                            Pris = 1899m,
                            Storlek = "S",
                            TillverkadAVID = 4,
                            Beskrivning = "Specialbeställd bröllopshatt med sidenrosett",
                            BildURL = ""
                        });
                });

            modelBuilder.Entity("AktivitetAnvändare", b =>
                {
                    b.HasOne("Models.Användare", null)
                        .WithMany()
                        .HasForeignKey("DeltagareAnvändarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Aktivitet", null)
                        .WithMany()
                        .HasForeignKey("DeltarIAktiviteterAktivitetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaterialMaterialBeställning", b =>
                {
                    b.HasOne("Models.MaterialBeställning", null)
                        .WithMany()
                        .HasForeignKey("MaterialBeställningID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialListaMaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaterialProdukt", b =>
                {
                    b.HasOne("Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialListaMaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Produkt", null)
                        .WithMany()
                        .HasForeignKey("ProduktID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Aktivitet", b =>
                {
                    b.HasOne("Models.Användare", "SkapadAv")
                        .WithMany("SkapadeAktiviteter")
                        .HasForeignKey("SkapadAvID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SkapadAv");
                });

            modelBuilder.Entity("Models.BestallningsRad", b =>
                {
                    b.HasOne("Models.MaterialBeställning", "Bestallning")
                        .WithMany("Rader")
                        .HasForeignKey("MaterialBeställningID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bestallning");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Models.MaterialBeställning", b =>
                {
                    b.HasOne("Models.Användare", "StartadAv")
                        .WithMany("materialBeställningsLista")
                        .HasForeignKey("StartadAvID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StartadAv");
                });

            modelBuilder.Entity("Models.Order", b =>
                {
                    b.HasOne("Models.Kund", "Kund")
                        .WithMany("Orders")
                        .HasForeignKey("KundID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Användare", "StartadAv")
                        .WithMany("orderLista")
                        .HasForeignKey("StartadAvID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kund");

                    b.Navigation("StartadAv");
                });

            modelBuilder.Entity("Models.OrderRad", b =>
                {
                    b.HasOne("Models.Order", "Order")
                        .WithMany("OrderRader")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Produkt", "Produkt")
                        .WithMany("OrderRader")
                        .HasForeignKey("ProduktID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("Models.Planering", b =>
                {
                    b.HasOne("Models.Användare", "Användare")
                        .WithMany("Planeringar")
                        .HasForeignKey("AnvändarID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.OrderRad", "OrderRad")
                        .WithMany("Planeringar")
                        .HasForeignKey("OrderRadID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Användare");

                    b.Navigation("OrderRad");
                });

            modelBuilder.Entity("Models.Produkt", b =>
                {
                    b.HasOne("Models.Användare", "TillverkadAv")
                        .WithMany("produktLista")
                        .HasForeignKey("TillverkadAVID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TillverkadAv");
                });

            modelBuilder.Entity("Models.Reklamation", b =>
                {
                    b.HasOne("Models.Kund", "Kund")
                        .WithMany()
                        .HasForeignKey("KundID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Produkt", "Produkt")
                        .WithMany()
                        .HasForeignKey("ProduktID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Models.Användare", "SkapadAv")
                        .WithMany()
                        .HasForeignKey("SkapadAvID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kund");

                    b.Navigation("Order");

                    b.Navigation("Produkt");

                    b.Navigation("SkapadAv");
                });

            modelBuilder.Entity("Models.Användare", b =>
                {
                    b.Navigation("Planeringar");

                    b.Navigation("SkapadeAktiviteter");

                    b.Navigation("materialBeställningsLista");

                    b.Navigation("orderLista");

                    b.Navigation("produktLista");
                });

            modelBuilder.Entity("Models.Kund", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Models.MaterialBeställning", b =>
                {
                    b.Navigation("Rader");
                });

            modelBuilder.Entity("Models.Order", b =>
                {
                    b.Navigation("OrderRader");
                });

            modelBuilder.Entity("Models.OrderRad", b =>
                {
                    b.Navigation("Planeringar");
                });

            modelBuilder.Entity("Models.Produkt", b =>
                {
                    b.Navigation("OrderRader");
                });
#pragma warning restore 612, 618
        }
    }
}
