// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DBcontext))]
    partial class DBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AktivitetAnvändare", b =>
                {
                    b.Property<int>("DeltagareAnvändarID")
                        .HasColumnType("int");

                    b.Property<int>("DeltarIAktiviteterAktivitetID")
                        .HasColumnType("int");

                    b.HasKey("DeltagareAnvändarID", "DeltarIAktiviteterAktivitetID");

                    b.HasIndex("DeltarIAktiviteterAktivitetID");

                    b.ToTable("AnvändarAktiviteter", (string)null);
                });

            modelBuilder.Entity("MaterialMaterialBeställning", b =>
                {
                    b.Property<int>("MaterialBeställningID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialListaMaterialID")
                        .HasColumnType("int");

                    b.HasKey("MaterialBeställningID", "MaterialListaMaterialID");

                    b.HasIndex("MaterialListaMaterialID");

                    b.ToTable("MaterialMaterialBeställning");
                });

            modelBuilder.Entity("MaterialProdukt", b =>
                {
                    b.Property<int>("MaterialListaMaterialID")
                        .HasColumnType("int");

                    b.Property<int>("ProduktID")
                        .HasColumnType("int");

                    b.HasKey("MaterialListaMaterialID", "ProduktID");

                    b.HasIndex("ProduktID");

                    b.ToTable("MaterialProdukt");
                });

            modelBuilder.Entity("Models.Aktivitet", b =>
                {
                    b.Property<int>("AktivitetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AktivitetID"));

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkapadAvID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SlutTid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTid")
                        .HasColumnType("datetime2");

                    b.HasKey("AktivitetID");

                    b.HasIndex("SkapadAvID");

                    b.ToTable("Aktiviteter");
                });

            modelBuilder.Entity("Models.Användare", b =>
                {
                    b.Property<int>("AnvändarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnvändarID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Lösenord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnvändarID");

                    b.ToTable("Användare");

                    b.HasData(
                        new
                        {
                            AnvändarID = 1,
                            Email = "ottoHattman@hotmail.com",
                            IsActive = true,
                            IsAdmin = true,
                            Lösenord = "$2a$11$QwJoMS2lWx8Fd7hor/EO9eCeEyBQ3Os6QxLxM2Vbt.DBAzug5lLvG",
                            Namn = "Otto",
                            Telefon = "07085652321"
                        },
                        new
                        {
                            AnvändarID = 2,
                            Email = "JudithHattman@hotmail.com",
                            IsActive = true,
                            IsAdmin = false,
                            Lösenord = "$2a$11$QwJoMS2lWx8Fd7hor/EO9eCeEyBQ3Os6QxLxM2Vbt.DBAzug5lLvG",
                            Namn = "Judith",
                            Telefon = "0727639856"
                        },
                        new
                        {
                            AnvändarID = 3,
                            Email = "MillieHattman@hotmail.com",
                            IsActive = true,
                            IsAdmin = false,
                            Lösenord = "$2a$11$QwJoMS2lWx8Fd7hor/EO9eCeEyBQ3Os6QxLxM2Vbt.DBAzug5lLvG",
                            Namn = "Millie",
                            Telefon = "0709825533"
                        },
                        new
                        {
                            AnvändarID = 4,
                            Email = "HerbertHattman@hotmail.com",
                            IsActive = true,
                            IsAdmin = false,
                            Lösenord = "$2a$11$QwJoMS2lWx8Fd7hor/EO9eCeEyBQ3Os6QxLxM2Vbt.DBAzug5lLvG",
                            Namn = "Herbert",
                            Telefon = "0705512322"
                        });
                });

            modelBuilder.Entity("Models.BestallningsRad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<int>("MaterialBeställningID")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialBeställningID");

                    b.HasIndex("MaterialId");

                    b.ToTable("BestallningsRader");
                });

            modelBuilder.Entity("Models.Kund", b =>
                {
                    b.Property<int>("KundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KundID"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FöretagsKund")
                        .HasColumnType("bit");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KundID");

                    b.ToTable("Kunder");

                    b.HasData(
                        new
                        {
                            KundID = 1001,
                            Adress = "Kullstigen 78",
                            Email = "Per.Larsson@hotmail.com",
                            FöretagsKund = true,
                            Land = "Sverige",
                            Namn = "Per Larsson",
                            Stad = "Stockholm",
                            Telefon = "076312129"
                        },
                        new
                        {
                            KundID = 1002,
                            Adress = "Milvägen 1",
                            Email = "Eva.Milen@hotmail.com",
                            FöretagsKund = true,
                            Land = "Sverige",
                            Namn = "Eva Von Milen",
                            Stad = "Stockholm",
                            Telefon = "0727728432"
                        },
                        new
                        {
                            KundID = 1003,
                            Adress = "Fjordaberg 51",
                            Email = "yvonne.fjord@hotmail.com",
                            FöretagsKund = false,
                            Land = "Finland",
                            Namn = "Yvonne Fjord",
                            Stad = "Helsingfors",
                            Telefon = "0702127345"
                        },
                        new
                        {
                            KundID = 1004,
                            Adress = "Javatorget 23",
                            Email = "ahmed.khan@hotmail.com",
                            FöretagsKund = false,
                            Land = "Sverige",
                            Namn = "Ahmed Khan",
                            Stad = "Örebro",
                            Telefon = "070123382"
                        },
                        new
                        {
                            KundID = 1005,
                            Adress = "Tetornet 3",
                            Email = "jasmin.barsk@hotmail.com",
                            FöretagsKund = false,
                            Land = "Sverige",
                            Namn = "Jasmin Barsk",
                            Stad = "Stockholm",
                            Telefon = "0702427373"
                        });
                });

            modelBuilder.Entity("Models.Material", b =>
                {
                    b.Property<int>("MaterialID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialID"));

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lagerantal")
                        .HasColumnType("int");

                    b.Property<string>("Mått")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaterialID");

                    b.ToTable("Material");

                    b.HasData(
                        new
                        {
                            MaterialID = 100001,
                            Beskrivning = "Inte filt man sover med",
                            Lagerantal = 23,
                            Mått = "meter",
                            Namn = "Filt",
                            Pris = 54m,
                            Typ = "Tyg"
                        },
                        new
                        {
                            MaterialID = 100002,
                            Beskrivning = "100% obesprutat bomull",
                            Lagerantal = 52,
                            Mått = "milimeter",
                            Namn = "Bomull",
                            Pris = 34m,
                            Typ = "Tyg"
                        },
                        new
                        {
                            MaterialID = 100003,
                            Beskrivning = "1.2 mm svar syträd av silikon och polyester",
                            Lagerantal = 2,
                            Mått = "meter",
                            Namn = "Svart tråd",
                            Pris = 28m,
                            Typ = "Tråd"
                        });
                });

            modelBuilder.Entity("Models.MaterialBeställning", b =>
                {
                    b.Property<int>("MaterialBeställningID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialBeställningID"));

                    b.Property<string>("Leverantör")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartadAvID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPris")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaterialBeställningID");

                    b.HasIndex("StartadAvID");

                    b.ToTable("MaterialBeställningar");

                    b.HasData(
                        new
                        {
                            MaterialBeställningID = 1000001,
                            Leverantör = "Kung AB",
                            StartadAvID = 1,
                            TotalPris = 1890m
                        },
                        new
                        {
                            MaterialBeställningID = 1000002,
                            Leverantör = "Kung AB",
                            StartadAvID = 2,
                            TotalPris = 769m
                        },
                        new
                        {
                            MaterialBeställningID = 1000003,
                            Leverantör = "Kung AB",
                            StartadAvID = 1,
                            TotalPris = 3419m
                        });
                });

            modelBuilder.Entity("Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Färdig")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FörväntadTillverkningsTid")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPrio")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpecialbeställning")
                        .HasColumnType("bit");

                    b.Property<int>("KundID")
                        .HasColumnType("int");

                    b.Property<double?>("Moms")
                        .HasColumnType("float");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rabatt")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StartadAvID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.HasIndex("KundID");

                    b.HasIndex("StartadAvID");

                    b.ToTable("Ordrar");

                    b.HasData(
                        new
                        {
                            OrderID = 100000001,
                            Datum = new DateTime(2024, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1001,
                            Pris = 1299m,
                            Rabatt = 0m,
                            StartadAvID = 1,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000002,
                            Datum = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1002,
                            Pris = 1099m,
                            Rabatt = 0m,
                            StartadAvID = 1,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000003,
                            Datum = new DateTime(2024, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1003,
                            Pris = 299m,
                            Rabatt = 0m,
                            StartadAvID = 1,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000004,
                            Datum = new DateTime(2024, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1004,
                            Pris = 2399m,
                            Rabatt = 0m,
                            StartadAvID = 1,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000005,
                            Datum = new DateTime(2024, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1005,
                            Pris = 779m,
                            Rabatt = 0m,
                            StartadAvID = 1,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000006,
                            Datum = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1001,
                            Pris = 949m,
                            Rabatt = 0m,
                            StartadAvID = 2,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000007,
                            Datum = new DateTime(2025, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1002,
                            Pris = 1049m,
                            Rabatt = 0m,
                            StartadAvID = 2,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000008,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1003,
                            Pris = 749m,
                            Rabatt = 0m,
                            StartadAvID = 2,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000009,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1004,
                            Pris = 999m,
                            Rabatt = 0m,
                            StartadAvID = 2,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000010,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1004,
                            Pris = 899m,
                            Rabatt = 0m,
                            StartadAvID = 2,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000011,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1005,
                            Pris = 1099m,
                            Rabatt = 0m,
                            StartadAvID = 2,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000012,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1001,
                            Pris = 2019m,
                            Rabatt = 0m,
                            StartadAvID = 3,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000013,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1002,
                            Pris = 1829m,
                            Rabatt = 0m,
                            StartadAvID = 3,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000014,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1003,
                            Pris = 599m,
                            Rabatt = 0m,
                            StartadAvID = 3,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000015,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1004,
                            Pris = 899m,
                            Rabatt = 0m,
                            StartadAvID = 3,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000016,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = true,
                            KundID = 1005,
                            Pris = 1299m,
                            Rabatt = 0m,
                            StartadAvID = 3,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000017,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1001,
                            Pris = 499m,
                            Rabatt = 0m,
                            StartadAvID = 4,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000018,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1002,
                            Pris = 499m,
                            Rabatt = 0m,
                            StartadAvID = 4,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000019,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1003,
                            Pris = 499m,
                            Rabatt = 0m,
                            StartadAvID = 4,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000020,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1004,
                            Pris = 499m,
                            Rabatt = 0m,
                            StartadAvID = 4,
                            Status = "Ej påbörjat"
                        },
                        new
                        {
                            OrderID = 100000021,
                            Datum = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Färdig = false,
                            FörväntadTillverkningsTid = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPrio = false,
                            IsSpecialbeställning = false,
                            KundID = 1005,
                            Pris = 499m,
                            Rabatt = 0m,
                            StartadAvID = 4,
                            Status = "Ej påbörjat"
                        });
                });

            modelBuilder.Entity("Models.Planering", b =>
                {
                    b.Property<int>("PlaneringsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaneringsID"));

                    b.Property<int>("AnvändarID")
                        .HasColumnType("int");

                    b.Property<string>("PlaneringsNamn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProduktID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SlutTid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTid")
                        .HasColumnType("datetime2");

                    b.HasKey("PlaneringsID");

                    b.HasIndex("AnvändarID");

                    b.HasIndex("ProduktID");

                    b.ToTable("Planeringar");
                });

            modelBuilder.Entity("Models.Produkt", b =>
                {
                    b.Property<int>("ProduktID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduktID"));

                    b.Property<string>("Decoration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Färdig")
                        .HasColumnType("bit");

                    b.Property<string>("Färg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HattTyp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lagerantal")
                        .HasColumnType("int");

                    b.Property<string>("Modell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProduktTyp")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Storlek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TillverkadAVID")
                        .HasColumnType("int");

                    b.HasKey("ProduktID");

                    b.HasIndex("TillverkadAVID");

                    b.ToTable("Produkter");

                    b.HasDiscriminator<string>("ProduktTyp").HasValue("Produkt");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("OrderProdukt", b =>
                {
                    b.Property<int>("OrdrarOrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProdukterProduktID")
                        .HasColumnType("int");

                    b.HasKey("OrdrarOrderID", "ProdukterProduktID");

                    b.HasIndex("ProdukterProduktID");

                    b.ToTable("OrderProdukter", (string)null);
                });

            modelBuilder.Entity("Models.LagerfördProdukt", b =>
                {
                    b.HasBaseType("Models.Produkt");

                    b.Property<string>("ArtikelID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Lagerförd");

                    b.HasData(
                        new
                        {
                            ProduktID = 10000001,
                            Decoration = "",
                            Färdig = false,
                            Färg = "",
                            HattTyp = "",
                            Lagerantal = 0,
                            Modell = "",
                            Namn = "Filt hatt",
                            Pris = 1099m,
                            Storlek = "M",
                            TillverkadAVID = 1,
                            ArtikelID = "LP0001",
                            Kategori = "Hatt"
                        },
                        new
                        {
                            ProduktID = 10000002,
                            Decoration = "",
                            Färdig = false,
                            Färg = "",
                            HattTyp = "",
                            Lagerantal = 0,
                            Modell = "",
                            Namn = "Siden keps",
                            Pris = 949m,
                            Storlek = "M",
                            TillverkadAVID = 2,
                            ArtikelID = "LP0002",
                            Kategori = "Keps"
                        });
                });

            modelBuilder.Entity("Models.SpecialBeställning", b =>
                {
                    b.HasBaseType("Models.Produkt");

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BildURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Special");
                });

            modelBuilder.Entity("AktivitetAnvändare", b =>
                {
                    b.HasOne("Models.Användare", null)
                        .WithMany()
                        .HasForeignKey("DeltagareAnvändarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Aktivitet", null)
                        .WithMany()
                        .HasForeignKey("DeltarIAktiviteterAktivitetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaterialMaterialBeställning", b =>
                {
                    b.HasOne("Models.MaterialBeställning", null)
                        .WithMany()
                        .HasForeignKey("MaterialBeställningID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialListaMaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaterialProdukt", b =>
                {
                    b.HasOne("Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialListaMaterialID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Produkt", null)
                        .WithMany()
                        .HasForeignKey("ProduktID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Aktivitet", b =>
                {
                    b.HasOne("Models.Användare", "SkapadAv")
                        .WithMany("SkapadeAktiviteter")
                        .HasForeignKey("SkapadAvID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SkapadAv");
                });

            modelBuilder.Entity("Models.BestallningsRad", b =>
                {
                    b.HasOne("Models.MaterialBeställning", "Bestallning")
                        .WithMany("Rader")
                        .HasForeignKey("MaterialBeställningID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bestallning");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Models.MaterialBeställning", b =>
                {
                    b.HasOne("Models.Användare", "StartadAv")
                        .WithMany("materialBeställningsLista")
                        .HasForeignKey("StartadAvID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StartadAv");
                });

            modelBuilder.Entity("Models.Order", b =>
                {
                    b.HasOne("Models.Kund", "Kund")
                        .WithMany("Orders")
                        .HasForeignKey("KundID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Användare", "StartadAv")
                        .WithMany("orderLista")
                        .HasForeignKey("StartadAvID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kund");

                    b.Navigation("StartadAv");
                });

            modelBuilder.Entity("Models.Planering", b =>
                {
                    b.HasOne("Models.Användare", "Användare")
                        .WithMany("Planeringar")
                        .HasForeignKey("AnvändarID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.Produkt", "Produkt")
                        .WithMany("Planeringar")
                        .HasForeignKey("ProduktID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Användare");

                    b.Navigation("Produkt");
                });

            modelBuilder.Entity("Models.Produkt", b =>
                {
                    b.HasOne("Models.Användare", "TillverkadAv")
                        .WithMany("produktLista")
                        .HasForeignKey("TillverkadAVID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TillverkadAv");
                });

            modelBuilder.Entity("OrderProdukt", b =>
                {
                    b.HasOne("Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdrarOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Produkt", null)
                        .WithMany()
                        .HasForeignKey("ProdukterProduktID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Användare", b =>
                {
                    b.Navigation("Planeringar");

                    b.Navigation("SkapadeAktiviteter");

                    b.Navigation("materialBeställningsLista");

                    b.Navigation("orderLista");

                    b.Navigation("produktLista");
                });

            modelBuilder.Entity("Models.Kund", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Models.MaterialBeställning", b =>
                {
                    b.Navigation("Rader");
                });

            modelBuilder.Entity("Models.Produkt", b =>
                {
                    b.Navigation("Planeringar");
                });
#pragma warning restore 612, 618
        }
    }
}
